export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS'
export const FETCHING_ERROR = 'FETCHING_ERROR'
export const FETCHING_START = 'FETCHING_START'

//Filtering
export const BRAND_TOGGLE = 'BRAND_TOGGLE'
export const STOCK_TOGGLE = 'STOCK_TOGGLE'
